---
# Will be overridden if it is possible to build ORCA
_build_xerces: False
_build_orca: False

build_core_count: "{{ ansible_facts['processor_vcpus'] }}"

xerces_default_config:
    repo_directory: "{{ ansible_env.HOME }}/workspace/gp-xerces"
    build_core_count: "{{ build_core_count }}"

    prefix: "/usr/local/"

orca_default_config:
    repo: https://github.com/greenplum-db/gporca
    repo_directory: "{{ ansible_env.HOME }}/workspace/gporca"
    repo_force: False
    repo_update: True
    build_core_count: "{{ build_core_count }}"

    prefix: "/usr/local/"

greenplum_default_config:
    repo: https://github.com/greenplum-db/gpdb
    repo_directory: "{{ansible_env.HOME}}/workspace/gpdb"
    repo_version: "HEAD"
    repo_force: False
    repo_update: False

    # Build flags
    use_orca: True
    enable_debug: True
    enable_cassert: True
    enable_gpcloud: True
    with_libxml: True
    cflags: "-O0 -fno-omit-frame-pointer"

    prefix: "/usr/local/gpdb"

    build_core_count: "{{ build_core_count }}"
