---
- set_fact:
    _greenplum_config: "{{ greenplum_default_config | combine(greenplum_config, recursive=True) }}"
  no_log: True
- set_fact:
    _xerces_config: "{{ xerces_default_config | combine(xerces_config, recursive=True) }}"
  no_log: True

- include: gp_xerces.yaml
  when: _greenplum_config.use_orca
