---
- name: Get configuration
  set_fact:
    _greenplum_config: "{{ greenplum_default_config | combine(greenplum_config, recursive=True) }}"
- set_fact:
    _orca_config: "{{ orca_default_config | combine(orca_config, recursive=True) }}"
- set_fact:
    _xerces_config: "{{ xerces_default_config | combine(xerces_config, recursive=True) }}"

- name: Get ORCA version for build
  set_fact:
    _orca_tag: "{{ _orca_config.orca_version_override }}"
  when: _greenplum_config.orca_version_override is defined

- slurp:
    src: "{{ _greenplum_config.repo_directory}}/concourse/tasks/compile_gpdb.yml"
  register: slurpfile
  when: _orca_tag is not defined
  ignore_errors: True

- set_fact:
    _orca_version: "{{ (slurpfile['content'] | b64decode | from_yaml).params.ORCA_TAG }}"
  when:
   - slurpfile['content'] is defined
   - slurpfile['content'] | b64decode | from_yaml is defined
   - (slurpfile['content'] | b64decode | from_yaml).params.ORCA_TAG is defined

- set_fact:
    _build_xerces: True
    _build_orca: True
  when:
    - _orca_version is defined
    - _greenplum_config.use_orca

- include: gp_xerces.yaml
  when: _build_xerces

